name: round_timer
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.8
  go_router: ^6.2.0
  flutter_native_splash: ^2.2.0+1
  path_provider: ^2.0.13
  keep_screen_on: ^2.1.0
  audioplayers: ^3.0.1
  timer_count_down: ^2.2.0
  quiver: ^3.2.1
  flutter_countdown_timer: ^4.1.0
  circular_countdown_timer: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2


flutter:

  uses-material-design: true
  assets:
    - assets/sounds/end.ogg
    - assets/sounds/start.ogg
    - assets/sounds/whistle.ogg
    - assets/images/setup.png
    - assets/images/box.png
    - assets/images/rest.png
    - assets/images/end.png
    - assets/icon/boxing-ring.png




